identifier: skean
name: Skean
url: https://github.com/krikun98/Skean
type: keyboard
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - ble
  - ieee802154
  - pwm
  - watchdog
  - gpio
